eureka:
  uri: http://localhost:8761/
  instance.preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    eviction-interval-timer-in-ms: 10000