server:
  port: 8761

eureka:
  instance:
    preferIpAddress: true
    hostname: http://localhost:8761/eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
#    register-with-eureka: false
#    fetch-registry: false
#
#spring:
#  freemarker:
#    template-loader-path: classpath:/templates/
#    prefer-file-system-access: false